import { useTranslation } from 'react-i18next';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { compactNumber, formatScore, relativeTime, sentimentMeta } from './redditData';
import { RedditEmptyState, RedditSkeleton } from './RedditStates';

function RailPanel({ title, children, className = '' }) { return <section className={`reddit-rail-panel ${className}`}><h2>{title}</h2>{children}</section>; }

export default function RedditIntelligenceRail({ sentiment, health, opportunities, contributors, loading, onConnector }) {
  const { t } = useTranslation();
  const chartData = sentiment?.distribution?.filter((item) => item.count > 0) || [];
  const connector = health?.connector;
  return <aside className="reddit-intelligence-rail">
    <RailPanel title="Sentiment Distribution" className="reddit-sentiment-panel">{loading ? <RedditSkeleton rows={2} /> : !chartData.length ? <RedditEmptyState title="No analyzed sentiment" detail="Sentiment appears after Reddit AI enrichment." /> : <><div className="reddit-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartData} dataKey="count" nameKey="label" innerRadius="58%" outerRadius="82%" paddingAngle={3}>{chartData.map((item) => <Cell key={item.label} fill={sentimentMeta(item.label).color} />)}</Pie><Tooltip formatter={(value, _name, payload) => [`${value} posts (${payload.payload.percent}%)`, payload.payload.label]} /></PieChart></ResponsiveContainer><div><strong>{compactNumber(sentiment.total_analyzed)}</strong><span>{t('analyzedPosts')}</span></div></div><ul className="reddit-sentiment-legend">{sentiment.distribution.map((item) => <li key={item.label}><i style={{ background: sentimentMeta(item.label).color }} />{sentimentMeta(item.label).label}<b>{item.percent}%</b></li>)}</ul><small>{sentiment.coverage}% enrichment coverage</small></>}</RailPanel>
    <RailPanel title="Reddit Connector Health">{loading ? <RedditSkeleton rows={2} /> : <div className="reddit-health-card"><div><span className={`reddit-health-logo ${connector?.status || 'unknown'}`}>●</span><p><strong>{t('redditViaApify')}</strong><small>{connector?.status === 'healthy' ? 'Operational' : connector?.status || 'Not configured'}</small></p><b className={connector?.status}>{connector?.status === 'healthy' ? 'Operational' : 'Attention'}</b></div><dl><dt>{t('lastChecked')}</dt><dd>{relativeTime(connector?.last_check)}</dd><dt>{t('dataFreshness')}</dt><dd>{relativeTime(health?.last_indexed_at)}</dd><dt>{t('analysisCoverage')}</dt><dd>{health?.analysis_coverage ?? 0}%</dd></dl><button type="button" onClick={onConnector}>{t('viewConnectorDetails')}</button></div>}</RailPanel>
    <RailPanel title="Top Opportunity Niches">{loading ? <RedditSkeleton rows={4} /> : !opportunities.length ? <RedditEmptyState title="No opportunity niches" detail="Opportunities appear after topics are enriched." /> : <ol className="reddit-ranked-list">{opportunities.slice(0, 5).map((item, index) => <li key={item.niche}><span>{index + 1}</span><div><strong>{item.niche.replaceAll('_', ' ')}</strong><small>{item.communities} communities · ↑ {compactNumber(item.momentum)}/h</small></div><b>{formatScore(item.opportunity_score)}</b></li>)}</ol>}</RailPanel>
    <RailPanel title="Top Contributors">{loading ? <RedditSkeleton rows={4} /> : !contributors.length ? <RedditEmptyState title="No contributor metadata" detail="New Reddit scans preserve author metadata." /> : <ol className="reddit-contributors">{contributors.slice(0, 5).map((item) => <li key={item.username}><span>{item.username.slice(0, 2).toUpperCase()}</span><div><strong>u/{item.username.replace(/^u\//, '')}</strong><small>{item.post_count} posts · {compactNumber(item.comment_count)} comments</small></div><b>↑ {compactNumber(item.momentum)}</b></li>)}</ol>}</RailPanel>
  </aside>;
}
