import { useTranslation } from 'react-i18next';
export default function RedditFilterBar({ filters, subreddits, onChange, onReset }) {
  const { t } = useTranslation();
  const change = (field, value) => onChange({ ...filters, [field]: value });
  const active = [filters.search, filters.subreddit, filters.sentiment, filters.min_upvotes > 0 ? `≥${filters.min_upvotes} upvotes` : '', filters.min_comments > 0 ? `≥${filters.min_comments} comments` : '', filters.min_opportunity > 0 ? `Score ≥${filters.min_opportunity}` : ''].filter(Boolean);
  return <section className="reddit-filter-bar" aria-label="Filter Reddit discussions">
    <div className="reddit-filter-controls"><label className="reddit-search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => change('search', event.target.value)} placeholder="Search posts, communities, authors, or topics…" /></label><label><span>{t('dateRange')}</span><select value={filters.days} onChange={(event) => change('days', Number(event.target.value))}><option value={7}>{t('last7Days')}</option><option value={30}>{t('last30Days')}</option><option value={90}>{t('last90Days')}</option><option value={365}>{t('lastYear')}</option></select></label><label><span>{t('subreddit')}</span><select value={filters.subreddit} onChange={(event) => change('subreddit', event.target.value)}><option value="">{t('allSubreddits')}</option>{subreddits.map((item) => <option key={item.name} value={item.name}>r/{item.name}</option>)}</select></label><label><span>{t('sentiment')}</span><select value={filters.sentiment} onChange={(event) => change('sentiment', event.target.value)}><option value="">{t('allSentiment')}</option><option value="positive">{t('positive')}</option><option value="neutral">{t('neutral')}</option><option value="negative">{t('negative')}</option><option value="mixed">{t('mixed')}</option></select></label><label className="reddit-score-filter"><span>{t('minOpportunity')}</span><input type="range" min="0" max="100" step="10" value={filters.min_opportunity} onChange={(event) => change('min_opportunity', Number(event.target.value))} /><b>{filters.min_opportunity}</b></label></div>
    <div className="reddit-active-filters"><span>{t('activeFilters')}</span>{active.length ? active.map((item) => <em key={item}>{item}</em>) : <small>{t('none')}</small>}{active.length > 0 && <button type="button" onClick={onReset}>{t('clearAll')}</button>}</div>
  </section>;
}
